# Generated by Django 5.2.1 on 2025-05-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_categorybatch_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_batch',
        ),
        migrations.DeleteModel(
            name='CategoryBatch',
        ),
    ]
